### ISSUE TITLE
Adding DependaBot

### ISSUE THREAD

**Issue by tiarebalbi** [gilbarbara/react-redux-saga-boilerplate#11]
Hi @gilbarbara,

What do you think in add [DependaBot](https://github.com/marketplace/dependabot) to this project? This will be good to keep all dependencies up-date...

**Comment by gilbarbara** [comment]
Are you from DependaBot? 🤔
Anyway, I've tried in one of my repos and I didn't like it. It opened 15 different PRs, one for each outdated dependency. If I let it installed, I'd have more dependaBot commits than my own.
