### ISSUE TITLE
Cannot get Semantic UI css to apply

### ISSUE THREAD

**Issue by AstromonkeyIO** [gilbarbara/react-redux-saga-boilerplate#16]
Hi there, I'm trying to use semantic ui: https://semantic-ui.com/ but running into some difficulties. I downloaded semantic ui and included the following in `assets/index.html`:
```
  <link rel="stylesheet" type="text/css" href="semantic/dist/semantic.min.css">
```.
However,  css classes from semantic ui does not seem to be applying. Is there something that I need to use when using third party css frameworks?

Thank you for reading my message and I hope to hear back soon.

**Comment by gilbarbara** [comment]
Not sure how would be the best approach to load it, but probably you'll need to include it in `app/scripts/index` so it can be processed in webpack and added to the bundle.
Something like `import 'semantic-ui/path/to/css';`
