### ISSUE TITLE
How can I debug the app?

### ISSUE THREAD

**Issue by bmnicolae** [gilbarbara/react-redux-saga-boilerplate#18]
Hello guys,

I'm trying to put a breakpoint into GitHub component and my Chrome line debug column is greyed out. Can you help me?

I'm using Chrome 66 with Javascript source maps enabled.

<img width="1669" alt="screen shot 2018-05-20 at 09 10 28" src="https://user-images.githubusercontent.com/10672395/40276244-acd94bda-5c0d-11e8-8bbe-4053ce3171a4.png">

**Comment by bmnicolae** [comment]
I'm no Webpack expert but to fix the problem I needed to change `devtool: 'cheap-module-source-map',` to `devtool: 'source-map',` in webpack.config.dev file.

**Comment by bmnicolae** [comment]
I'm no Webpack expert but to fix the problem I needed to change `devtool: 'cheap-module-source-map',` to `devtool: 'source-map',` in webpack.config.dev.js file.

Thank you for your hard work!  👍 

You can now close the issue 😃.

**Comment by gilbarbara** [comment]
hey @bmnicolae 

Using `source-map` with development is costly and will increase bundle time for every minimal change.

As an option, you could add a [debugger](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/debugger) statement directly in the code.

**Comment by bmnicolae** [comment]
Thank you!
