### ISSUE TITLE
Recommendation for subroutes

### ISSUE THREAD

**Issue by ayxos** [gilbarbara/react-redux-saga-boilerplate#24]
I am creating a SPA with your boilerplate. I have a dashboard with a menu that contains multiple sections and subsections. For each one of those private sections, I have a new container and a new route, but that does make no sense. I want to reuse the private route with different containers. 

Is my approach ok? what would be the best approach?

Thanks

**Comment by gilbarbara** [comment]
There's not a single universal approach for it.
But if a route is public or private, this shouldn't make any difference for component/directory organization.
