### ISSUE TITLE
Not Found: flatmap-stream@0.1.2

### ISSUE THREAD

**Issue by ayrasys** [gilbarbara/react-redux-saga-boilerplate#38]
npm install 
command show this error .. 
Not Found: flatmap-stream@0.1.2

how to fix it .
Thanks

**Comment by gilbarbara** [comment]
Hey
I just a fresh install of the latest version (f124e57a56ee608f4c1f5f9c6f336f91260892c1) successfully. Using node 11.3 with npm 6.4.1
