### ISSUE TITLE
npm run build is not working on Windows

### ISSUE THREAD

**Issue by ravi100k** [gilbarbara/react-redux-saga-boilerplate#42]
![image](https://user-images.githubusercontent.com/21195445/54070750-1a8ed880-428a-11e9-858a-7e587f56e511.png)

While running npm run build I am getting this error.
I am on 
windows 64bit system
node version = 11.10.0
npm version = 6.7.0

**Comment by gilbarbara** [comment]
I think this might be a Windows-only problem and I don't have a PC to test/fix it.
Feel free to submit a PR.

**Comment by gilbarbara** [comment]
The error doesn't say that the `config.publicPath` is wrong but that some `path` variable is not a string...

Maybe the `process.cwd()` in this [line](https://github.com/gilbarbara/react-redux-saga-boilerplate/blob/master/tools/build.js#L155) doesn't work as expected on Windows?

**Comment by gilbarbara** [comment]
Did you ever tried to build a `create-react-app` installation? Does it build correctly?
Which shell are you using? Powershell, bash?

**Comment by ravi100k** [comment]
> Did you ever tried to build a create-react-app installation? Does it build correctly?
Yes, always.
> Which shell are you using? Powershell, bash?
PS
> Maybe the process.cwd()
It returns the type string only, I have checked it.

I am checking for some other solution.

**Comment by chrisVillanueva** [comment]
> The error doesn't say that the `config.publicPath` is wrong but that some `path` variable is not a string...
> 
> Maybe the `process.cwd()` in this [line](https://github.com/gilbarbara/react-redux-saga-boilerplate/blob/master/tools/build.js#L155) doesn't work as expected on Windows?

`process.cwd()` return value looks correct on my Win10 machine:

![image](https://user-images.githubusercontent.com/1554280/56760589-244c9c80-6761-11e9-83d2-c7ff8b69817c.png)


BTW, I'm using git bash.

**Comment by chrisVillanueva** [comment]
screenshots:
![image](https://user-images.githubusercontent.com/1554280/56767858-692cff00-6772-11e9-985a-2ec81fe16d46.png)
![image](https://user-images.githubusercontent.com/1554280/56767889-79dd7500-6772-11e9-9d28-112bfe938bb5.png)

**Comment by achoura** [comment]
same issue here on Ubuntu 18.04 with npm version 6.4.1
