### ISSUE TITLE
Multiple Environments

### ISSUE THREAD

**Issue by AmitGehelot** [gilbarbara/react-redux-saga-boilerplate#45]
Hi GilBarbara, thank you for the awesome boilerplate. Can you tell me how to set up environment for staging , QA etc? Need to have separate set of API urls for each of them.

**Comment by gilbarbara** [comment]
Hey! Thanks! :)

I usually set an `APP_ENV` environment with multiple build scripts in my package.json:

```json
{
  "scripts": {
    "build": "node tools/build",
    "build:qa": "APP_ENV=qa npm run build",
    "build:production": "APP_ENV=production npm run build"
  }
}
```

and in config.js I set variables per environment:
```js
const config = {
  apiUrl: 'https://api-dev.example.com/v1'
};

if (process.env.APP_ENV === 'qa') {
  config.apiUrl = 'https://api-qa.example.com/v1';
}

/* istanbul ignore if */
if (process.env.APP_ENV === 'production') {
  config.apiUrl = 'https://api.example.com/v1';
}

module.exports = config;

```

Does that work for you?

**Comment by AmitGehelot** [comment]
Thank you!

**Comment by AmitGehelot** [comment]
Hi, in config, process.env.APP_ENV comes as undefined.

**Comment by AmitGehelot** [comment]
Resolved it by using REACT_APP_ENV instead of APP_ENV
