### ISSUE TITLE
Collator could not be initialised and wouldn't be used.

### ISSUE THREAD

**Issue by manojchowdary27** [gilbarbara/react-redux-saga-boilerplate#46]
Hi,

I just cloned the repo and installed the node modules using **npm install**. It is working fine in the modern browsers but not working in the IE 11.

Error in the console is "Collator could not be initialised and wouldn't be used."

Steps to reproduce
1. Clone the repo.
2. npm i
3. npm start
4. open IE11 and check

Thanks.

**Comment by gilbarbara** [comment]
Development mode will never work with legacy browsers

**Comment by manojchowdary27** [comment]
Even Build mode is not working
