### ISSUE TITLE
Can not be used React.lazy or react_loadable

### ISSUE THREAD

**Issue by duongvancuong** [gilbarbara/react-redux-saga-boilerplate#48]
![Screenshot from 2019-05-23 15-15-35](https://user-images.githubusercontent.com/19904857/58236712-ae425200-7d6d-11e9-96f9-4d666f556923.png)

I can not run npm start or build when using ``React.lazy()`` or [https://github.com/jamiebuilds/react-loadable](react-loadable).

Can you help?
Thanks

**Comment by duongvancuong** [comment]
I fixed it, this issue https://github.com/webpack/webpack/issues/8656
 but I still don't understand why.

**Comment by gilbarbara** [comment]
The bug is described in that issue.
