### ISSUE TITLE
Not able to create production build

### ISSUE THREAD

**Issue by chaitanya-y** [gilbarbara/react-redux-saga-boilerplate#51]
Errors:
1.  (node:4444) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
Failed to compile.

chunk scripts/bundle [entry]
({
              chunk: chunkData
            }) => this.options.moduleFilename(chunkData)
output.replace is not a function

2.  Cannot destructure property `createHash` of 'undefined' or 'null'.

**Comment by gilbarbara** [comment]
Did you upgrade any dependencies or added new ones?

**Comment by chaitanya-y** [comment]
yes. I just added third party libraries. I did not touch webpack and  all. Thanks

**Comment by gilbarbara** [comment]
I discovered a bug in one of the dependencies, I'll update it soon.
