### ISSUE TITLE
How to deploy in production?

### ISSUE THREAD

**Issue by dmajumder4292** [gilbarbara/react-redux-saga-boilerplate#55]
Since it is not using react-scripts, I believe something else have to be done to deploy it in production. When I deploy it on the server, I generate the build folder and do npm start, but that is starting the dev server, which should not happen in production. What should I do instead?

Please help

**Comment by rodrigobacelli** [comment]
react-scripts does not deploy your project for you. But you can follow their guide (here)[https://create-react-app.dev/docs/deployment/] and expect the same results as in react-scripts.

Explaining: Building the project just generates static files as react-scripts do. As you can use them anywhere, so, where and how you will deploy them is up to you to chose and implement.

**Comment by gilbarbara** [comment]
Exactly what @rodrigobacelli said.
Run `npm run build` and deploy it wherever you like.
This package won't take care of that.
