### ISSUE TITLE
Cache problem for production build and build is not updating until we refresh

### ISSUE THREAD

**Issue by abhijitkc** [gilbarbara/react-redux-saga-boilerplate#58]
There is cache problem for production build and build is not updating until we refresh once new build upload.

**Comment by gilbarbara** [comment]
Hey,

I think this is related to the service-worker caching. If it is, that's how it [works](https://developers.google.com/web/ilt/pwa/introduction-to-service-worker#what_can_service_workers_do).

When you deploy a new version the browser will use the cached files and identify there are changes and apply the new version. However, it won't load it until the next refresh

**Comment by gilbarbara** [comment]
You can remove it, but then your app won't be a PWA.

**Comment by abhijitkc** [comment]
Okay. Can you please guide me, how to remove that from this boilerplate? As I have tried it using "unregister()" function instead of "register()" in "index.jsx" file. But it still cache my files on production server.

**Comment by gilbarbara** [comment]
Hey,

Just running `unregister()` should do the trick. Also, check the Application tab in Chrome's DevTools to make sure there is no active service worker.
If that doesn't work, check the document for the `workbox-webpack-plugin`.
