### ISSUE TITLE
How to add scss files in bundle

### ISSUE THREAD

**Issue by abhijitkc** [gilbarbara/react-redux-saga-boilerplate#59]
Currently I have created scss folder in /assets and included the files in App.jsx. But when I create build those files comes under local path /home/test-test/mw-react-new/react-app/assets/ in source in google Chrome. So what is proper way to include scss files and how to add those files in bundle?

**Comment by gilbarbara** [comment]
Hey,

I'm not sure I understood your question...
Files in the `assets` directory usually aren't processed by webpack, just copied in the build process.
You might need to move them to the `src` directory and update your webpack.config.js to handle them.

[s]
