### ISSUE TITLE
Can not `npm run build` ENAMETOOLONG error

### ISSUE THREAD

**Issue by minhnv2306** [gilbarbara/react-redux-saga-boilerplate#64]
Hello contributors!

I try run `npm run build` at production and get the error

**ENAMETOOLONG: name too long, open '/usr/share/nginx/build/static/svg+xml;base64,PHN2ZyB3aWR0aD0iMTYiIGhlaWdodD0iMTYiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHBhdGggZD0iTTE0LjUgMi41aC0xM0EuNS41IDAgMDAxIDN2MTBhLjUuNSAwIDAwLjUuNWgxM2EuNS41IDAgMDAuNS0uNVYzYS41LjUgMCAwMC0uNS0uNXpNNS4yODEgNC43NWExIDEgMCAwMTAgMiAxIDEgMCAwMTAtMnptOC4wMyA2LjgzYS4xMjcuMTI3IDAgMDEtLjA4MS4wM0gyLjc2OWEuMTI1LjEyNSAwIDAxLS4wOTYtLjIwN2wyLjY2MS0zLjE1NmEuMTI2LjEyNiAwIDAxLjE3Ny0uMDE2bC4wMTYuMDE2TDcuMDggMTAuMDlsMi40Ny0yLjkzYS4xMjYuMTI2IDAgMDEuMTc3LS4wMTZsLjAxNS4wMTYgMy41ODggNC4yNDRhLjEyNy4xMjcgMCAwMS0uMDIuMTc1eiIgZmlsbD0iIzhDOEM4QyIvPjwvc3ZnPg==.8703e22.bin'**

Could you know the reason? My env
- Node Version: 16.18
- Machine: EC2 AWS

**Comment by gilbarbara** [comment]
The error doesn't seem to be caused by this boilerplate. `/usr/share/nginx/build/...`
