### ISSUE TITLE
.ENV File

### ISSUE THREAD

**Issue by tanmayk92** [gilbarbara/react-redux-saga-boilerplate#67]
Can you share your version of the .env file here for future reference. As while running `npm run build` the js folder inside build is just producing main..js without the hash.

**Comment by gilbarbara** [comment]
You don't need a `.env` file to build.
The hash isn't dependent on that and just cloned the repo, installed the dependencies, and built it without problems.

**Comment by tanmayk92** [comment]
Hey @gilbarbara Thanks for your attention, but the js files are getting bundled without the hash and named as main..js

**Comment by tanmayk92** [comment]
Hey @gilbarbara Thanks for your attention, Can you pls check the CSS issue, the build is getting built without the CSS files.
