### ISSUE TITLE
Issue resolving styled-minimal in boilerplate

### ISSUE THREAD

**Issue by tanmayk92** [gilbarbara/react-redux-saga-boilerplate#69]
When you checkout the project and run npm install, there is an error as Cannot resolve react in styled-minimal dependency. Unable to resolve Dependency Tree. 
Can you pls check.

**Comment by gilbarbara** [comment]
Hey @tanmayk92 
This is an old boilerplate that hasn't been updated for quite some time.

```shell
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

As the error says, you can run `npm install --legacy-peer-deps` to fix this (and probably other install errors)

**Comment by tanmayk92** [comment]
@gilbarbara This is creating issue while deploying to azure portal, as the azure deployment runs preinstalled npm install command. Can you pls fix this issue regarding dependencies ?

**Comment by gilbarbara** [comment]
@tanmayk92 
This is a boilerplate. Once you start customizing it, there's no way to update your local copy anymore.
`styled-minimal` minimal is deprecated, so there's no way to fix it.
You can try replacing it with [@ilbarbara/components](https://github.com/gilbarbara/components), which has a similar API or any other react ui-kit.
